-- ============================================================
-- V10: Comprehensive world airport seed (~400 major airports)
-- INSERT IGNORE keeps existing records intact (Amadeus sync wins).
-- ============================================================

INSERT IGNORE INTO airports (airport_code, airport_name, city, country, timezone) VALUES

-- ═══════════════════════════════════════════════════════════
-- NORTH AMERICA — United States
-- ═══════════════════════════════════════════════════════════
('ATL','Hartsfield-Jackson Atlanta International','Atlanta','United States','America/New_York'),
('LAX','Los Angeles International','Los Angeles','United States','America/Los_Angeles'),
('ORD','O\'Hare International','Chicago','United States','America/Chicago'),
('DFW','Dallas/Fort Worth International','Dallas','United States','America/Chicago'),
('DEN','Denver International','Denver','United States','America/Denver'),
('JFK','John F. Kennedy International','New York','United States','America/New_York'),
('SFO','San Francisco International','San Francisco','United States','America/Los_Angeles'),
('SEA','Seattle-Tacoma International','Seattle','United States','America/Los_Angeles'),
('LAS','Harry Reid International','Las Vegas','United States','America/Los_Angeles'),
('MCO','Orlando International','Orlando','United States','America/New_York'),
('MIA','Miami International','Miami','United States','America/New_York'),
('PHX','Phoenix Sky Harbor International','Phoenix','United States','America/Phoenix'),
('EWR','Newark Liberty International','Newark','United States','America/New_York'),
('IAH','George Bush Intercontinental','Houston','United States','America/Chicago'),
('BOS','Logan International','Boston','United States','America/New_York'),
('MSP','Minneapolis-Saint Paul International','Minneapolis','United States','America/Chicago'),
('DTW','Detroit Metropolitan Wayne County','Detroit','United States','America/Detroit'),
('FLL','Fort Lauderdale-Hollywood International','Fort Lauderdale','United States','America/New_York'),
('CLT','Charlotte Douglas International','Charlotte','United States','America/New_York'),
('SLC','Salt Lake City International','Salt Lake City','United States','America/Denver'),
('BWI','Baltimore/Washington International','Baltimore','United States','America/New_York'),
('SAN','San Diego International','San Diego','United States','America/Los_Angeles'),
('TPA','Tampa International','Tampa','United States','America/New_York'),
('IAD','Washington Dulles International','Washington DC','United States','America/New_York'),
('DCA','Ronald Reagan Washington National','Washington DC','United States','America/New_York'),
('MDW','Chicago Midway International','Chicago','United States','America/Chicago'),
('PDX','Portland International','Portland','United States','America/Los_Angeles'),
('HNL','Daniel K. Inouye International','Honolulu','United States','Pacific/Honolulu'),
('STL','St. Louis Lambert International','St. Louis','United States','America/Chicago'),
('MCI','Kansas City International','Kansas City','United States','America/Chicago'),
('RDU','Raleigh-Durham International','Raleigh','United States','America/New_York'),
('PHL','Philadelphia International','Philadelphia','United States','America/New_York'),
('MSY','Louis Armstrong New Orleans International','New Orleans','United States','America/Chicago'),
('AUS','Austin-Bergstrom International','Austin','United States','America/Chicago'),
('BNA','Nashville International','Nashville','United States','America/Chicago'),
('SMF','Sacramento International','Sacramento','United States','America/Los_Angeles'),
('OAK','Oakland Metropolitan International','Oakland','United States','America/Los_Angeles'),
('SJC','Norman Y. Mineta San Jose International','San Jose','United States','America/Los_Angeles'),
('ABQ','Albuquerque International Sunport','Albuquerque','United States','America/Denver'),
('ANC','Ted Stevens Anchorage International','Anchorage','United States','America/Anchorage'),
('OGG','Kahului Airport','Maui','United States','Pacific/Honolulu'),
('PIT','Pittsburgh International','Pittsburgh','United States','America/New_York'),
('CMH','John Glenn Columbus International','Columbus','United States','America/New_York'),
('CLE','Cleveland Hopkins International','Cleveland','United States','America/New_York'),
('IND','Indianapolis International','Indianapolis','United States','America/Indiana/Indianapolis'),
('BDL','Bradley International','Hartford','United States','America/New_York'),
('MEM','Memphis International','Memphis','United States','America/Chicago'),
('ELP','El Paso International','El Paso','United States','America/Denver'),
('TUS','Tucson International','Tucson','United States','America/Phoenix'),
('BUF','Buffalo Niagara International','Buffalo','United States','America/New_York'),
('ORF','Norfolk International','Norfolk','United States','America/New_York'),
('RIC','Richmond International','Richmond','United States','America/New_York'),
('OMA','Eppley Airfield','Omaha','United States','America/Chicago'),
('GRR','Gerald R. Ford International','Grand Rapids','United States','America/Detroit'),
('BOI','Boise Airport','Boise','United States','America/Boise'),
('MKE','Milwaukee Mitchell International','Milwaukee','United States','America/Chicago'),

-- Canada
('YYZ','Toronto Pearson International','Toronto','Canada','America/Toronto'),
('YUL','Montreal-Pierre Elliott Trudeau International','Montreal','Canada','America/Toronto'),
('YVR','Vancouver International','Vancouver','Canada','America/Vancouver'),
('YYC','Calgary International','Calgary','Canada','America/Edmonton'),
('YEG','Edmonton International','Edmonton','Canada','America/Edmonton'),
('YOW','Ottawa Macdonald-Cartier International','Ottawa','Canada','America/Toronto'),
('YHZ','Halifax Stanfield International','Halifax','Canada','America/Halifax'),
('YQB','Quebec City Jean Lesage International','Quebec City','Canada','America/Toronto'),
('YWG','Winnipeg James Armstrong Richardson International','Winnipeg','Canada','America/Winnipeg'),
('YXE','Saskatoon John G. Diefenbaker International','Saskatoon','Canada','America/Regina'),
('YZF','Yellowknife Airport','Yellowknife','Canada','America/Yellowknife'),
('YFB','Iqaluit Airport','Iqaluit','Canada','America/Iqaluit'),

-- Mexico
('MEX','Mexico City International','Mexico City','Mexico','America/Mexico_City'),
('GDL','Miguel Hidalgo y Costilla Guadalajara International','Guadalajara','Mexico','America/Mexico_City'),
('MTY','Monterrey General Mariano Escobedo International','Monterrey','Mexico','America/Monterrey'),
('CUN','Cancun International','Cancun','Mexico','America/Cancun'),
('SJD','Los Cabos International','San Jose del Cabo','Mexico','America/Mazatlan'),
('PVR','Licenciado Gustavo Díaz Ordaz International','Puerto Vallarta','Mexico','America/Mexico_City'),
('MZT','General Rafael Buelna International','Mazatlan','Mexico','America/Mazatlan'),

-- ═══════════════════════════════════════════════════════════
-- CARIBBEAN & CENTRAL AMERICA
-- ═══════════════════════════════════════════════════════════
('NAS','Lynden Pindling International','Nassau','Bahamas','America/Nassau'),
('MBJ','Sangster International','Montego Bay','Jamaica','America/Jamaica'),
('KIN','Norman Manley International','Kingston','Jamaica','America/Jamaica'),
('SJU','Luis Munoz Marin International','San Juan','Puerto Rico','America/Puerto_Rico'),
('SDQ','Las Americas International','Santo Domingo','Dominican Republic','America/Santo_Domingo'),
('PUJ','Punta Cana International','Punta Cana','Dominican Republic','America/Santo_Domingo'),
('HAV','Jose Marti International','Havana','Cuba','America/Havana'),
('BGI','Grantley Adams International','Bridgetown','Barbados','America/Barbados'),
('POS','Piarco International','Port of Spain','Trinidad and Tobago','America/Port_of_Spain'),
('SXM','Princess Juliana International','Sint Maarten','Sint Maarten','America/Lower_Princes'),
('GCM','Owen Roberts International','Georgetown','Cayman Islands','America/Cayman'),
('SLU','Hewanorra International','Vieux Fort','Saint Lucia','America/St_Lucia'),
('ANU','V.C. Bird International','St. John\'s','Antigua and Barbuda','America/Antigua'),
('PTY','Tocumen International','Panama City','Panama','America/Panama'),
('GUA','La Aurora International','Guatemala City','Guatemala','America/Guatemala'),
('SAL','El Salvador International','San Salvador','El Salvador','America/El_Salvador'),
('MGA','Augusto C. Sandino International','Managua','Nicaragua','America/Managua'),
('SJO','Juan Santamaria International','San Jose','Costa Rica','America/Costa_Rica'),
('SAP','Ramón Villeda Morales International','San Pedro Sula','Honduras','America/Tegucigalpa'),
('TGU','Toncontin International','Tegucigalpa','Honduras','America/Tegucigalpa'),
('BZE','Philip S. W. Goldson International','Belize City','Belize','America/Belize'),

-- ═══════════════════════════════════════════════════════════
-- SOUTH AMERICA
-- ═══════════════════════════════════════════════════════════
('GRU','Sao Paulo/Guarulhos International','São Paulo','Brazil','America/Sao_Paulo'),
('GIG','Rio de Janeiro/Galeao International','Rio de Janeiro','Brazil','America/Sao_Paulo'),
('BSB','Presidente Juscelino Kubitschek International','Brasilia','Brazil','America/Sao_Paulo'),
('SSA','Luis Eduardo Magalhaes International','Salvador','Brazil','America/Bahia'),
('FOR','Pinto Martins International','Fortaleza','Brazil','America/Fortaleza'),
('REC','Guararapes International','Recife','Brazil','America/Recife'),
('CWB','Afonso Pena International','Curitiba','Brazil','America/Sao_Paulo'),
('POA','Salgado Filho International','Porto Alegre','Brazil','America/Sao_Paulo'),
('MAO','Eduardo Gomes International','Manaus','Brazil','America/Manaus'),
('VCP','Viracopos International','Campinas','Brazil','America/Sao_Paulo'),
('BEL','Val de Cans International','Belem','Brazil','America/Belem'),
('EZE','Ministro Pistarini International','Buenos Aires','Argentina','America/Argentina/Buenos_Aires'),
('AEP','Aeroparque Jorge Newbery','Buenos Aires','Argentina','America/Argentina/Buenos_Aires'),
('COR','Ingeniero Aeronautico Ambrosio L.V. Taravella','Cordoba','Argentina','America/Argentina/Cordoba'),
('MDZ','El Plumerillo International','Mendoza','Argentina','America/Argentina/Mendoza'),
('USH','Malvinas Argentinas International','Ushuaia','Argentina','America/Argentina/Ushuaia'),
('SCL','Arturo Merino Benitez International','Santiago','Chile','America/Santiago'),
('IQQ','Diego Aracena International','Iquique','Chile','America/Santiago'),
('ANF','Cerro Moreno International','Antofagasta','Chile','America/Santiago'),
('BOG','El Dorado International','Bogota','Colombia','America/Bogota'),
('MDE','Jose Maria Cordova International','Medellin','Colombia','America/Bogota'),
('CTG','Rafael Nunez International','Cartagena','Colombia','America/Bogota'),
('CLO','Alfonso Bonilla Aragon International','Cali','Colombia','America/Bogota'),
('LIM','Jorge Chavez International','Lima','Peru','America/Lima'),
('CUZ','Alejandro Velasco Astete International','Cusco','Peru','America/Lima'),
('AQP','Rodriguez Ballon International','Arequipa','Peru','America/Lima'),
('GYE','Jose Joaquin de Olmedo International','Guayaquil','Ecuador','America/Guayaquil'),
('UIO','Mariscal Sucre International','Quito','Ecuador','America/Guayaquil'),
('CCS','Simon Bolivar International','Caracas','Venezuela','America/Caracas'),
('VLN','Arturo Michelena International','Valencia','Venezuela','America/Caracas'),
('LPB','El Alto International','La Paz','Bolivia','America/La_Paz'),
('VVI','Viru Viru International','Santa Cruz','Bolivia','America/La_Paz'),
('ASU','Silvio Pettirossi International','Asuncion','Paraguay','America/Asuncion'),
('MVD','Carrasco International','Montevideo','Uruguay','America/Montevideo'),
('PBM','Johan Adolf Pengel International','Paramaribo','Suriname','America/Paramaribo'),
('GEO','Cheddi Jagan International','Georgetown','Guyana','America/Guyana'),
('CAY','Felix Eboue Airport','Cayenne','French Guiana','America/Cayenne'),

-- ═══════════════════════════════════════════════════════════
-- EUROPE — Western
-- ═══════════════════════════════════════════════════════════
('LHR','Heathrow Airport','London','United Kingdom','Europe/London'),
('LGW','Gatwick Airport','London','United Kingdom','Europe/London'),
('STN','London Stansted Airport','London','United Kingdom','Europe/London'),
('LTN','London Luton Airport','London','United Kingdom','Europe/London'),
('LCY','London City Airport','London','United Kingdom','Europe/London'),
('MAN','Manchester Airport','Manchester','United Kingdom','Europe/London'),
('EDI','Edinburgh Airport','Edinburgh','United Kingdom','Europe/London'),
('GLA','Glasgow Airport','Glasgow','United Kingdom','Europe/London'),
('BHX','Birmingham Airport','Birmingham','United Kingdom','Europe/London'),
('BRS','Bristol Airport','Bristol','United Kingdom','Europe/London'),
('CDG','Paris Charles de Gaulle Airport','Paris','France','Europe/Paris'),
('ORY','Paris Orly Airport','Paris','France','Europe/Paris'),
('LYS','Lyon-Saint Exupery Airport','Lyon','France','Europe/Paris'),
('MRS','Marseille Provence Airport','Marseille','France','Europe/Paris'),
('NCE','Nice Cote d\'Azur Airport','Nice','France','Europe/Paris'),
('TLS','Toulouse-Blagnac Airport','Toulouse','France','Europe/Paris'),
('BOD','Bordeaux-Merignac Airport','Bordeaux','France','Europe/Paris'),
('AMS','Amsterdam Airport Schiphol','Amsterdam','Netherlands','Europe/Amsterdam'),
('FRA','Frankfurt Airport','Frankfurt','Germany','Europe/Berlin'),
('MUC','Munich Airport','Munich','Germany','Europe/Berlin'),
('BER','Berlin Brandenburg Airport','Berlin','Germany','Europe/Berlin'),
('DUS','Dusseldorf Airport','Dusseldorf','Germany','Europe/Berlin'),
('HAM','Hamburg Airport','Hamburg','Germany','Europe/Berlin'),
('STR','Stuttgart Airport','Stuttgart','Germany','Europe/Berlin'),
('CGN','Cologne Bonn Airport','Cologne','Germany','Europe/Berlin'),
('NUE','Nuremberg Airport','Nuremberg','Germany','Europe/Berlin'),
('ZRH','Zurich Airport','Zurich','Switzerland','Europe/Zurich'),
('GVA','Geneva Airport','Geneva','Switzerland','Europe/Zurich'),
('VIE','Vienna International Airport','Vienna','Austria','Europe/Vienna'),
('SZG','Salzburg Airport','Salzburg','Austria','Europe/Vienna'),
('BRU','Brussels Airport','Brussels','Belgium','Europe/Brussels'),
('LUX','Luxembourg Airport','Luxembourg','Luxembourg','Europe/Luxembourg'),
('MAD','Adolfo Suarez Madrid-Barajas Airport','Madrid','Spain','Europe/Madrid'),
('BCN','Barcelona El Prat Airport','Barcelona','Spain','Europe/Madrid'),
('PMI','Palma de Mallorca Airport','Palma','Spain','Europe/Madrid'),
('AGP','Malaga Airport','Malaga','Spain','Europe/Madrid'),
('IBZ','Ibiza Airport','Ibiza','Spain','Europe/Madrid'),
('VLC','Valencia Airport','Valencia','Spain','Europe/Madrid'),
('SVQ','Seville Airport','Seville','Spain','Europe/Madrid'),
('TFN','Tenerife Norte Airport','Tenerife','Spain','Atlantic/Canary'),
('TFS','Tenerife Sur Airport','Tenerife','Spain','Atlantic/Canary'),
('LPA','Gran Canaria Airport','Las Palmas','Spain','Atlantic/Canary'),
('LIS','Lisbon Humberto Delgado Airport','Lisbon','Portugal','Europe/Lisbon'),
('OPO','Francisco Sa Carneiro Airport','Porto','Portugal','Europe/Lisbon'),
('FAO','Faro Airport','Faro','Portugal','Europe/Lisbon'),
('FCO','Rome Fiumicino Leonardo da Vinci Airport','Rome','Italy','Europe/Rome'),
('CIA','Rome Ciampino Airport','Rome','Italy','Europe/Rome'),
('MXP','Milan Malpensa Airport','Milan','Italy','Europe/Rome'),
('LIN','Milan Linate Airport','Milan','Italy','Europe/Rome'),
('BGY','Orio al Serio Airport','Bergamo','Italy','Europe/Rome'),
('NAP','Naples International Airport','Naples','Italy','Europe/Rome'),
('VCE','Venice Marco Polo Airport','Venice','Italy','Europe/Rome'),
('BLQ','Bologna Guglielmo Marconi Airport','Bologna','Italy','Europe/Rome'),
('CTA','Catania Fontanarossa Airport','Catania','Italy','Europe/Rome'),
('PMO','Palermo Falcone-Borsellino Airport','Palermo','Italy','Europe/Rome'),
('ATH','Athens Eleftherios Venizelos International','Athens','Greece','Europe/Athens'),
('SKG','Thessaloniki Macedonia International','Thessaloniki','Greece','Europe/Athens'),
('HER','Heraklion Nikos Kazantzakis International','Heraklion','Greece','Europe/Athens'),
('CFU','Corfu Ioannis Kapodistrias International','Corfu','Greece','Europe/Athens'),
('RHO','Rhodes Diagoras International','Rhodes','Greece','Europe/Athens'),
('KGS','Kos Island International','Kos','Greece','Europe/Athens'),
('JTR','Santorini Thira National Airport','Santorini','Greece','Europe/Athens'),
('JMK','Mykonos Island National Airport','Mykonos','Greece','Europe/Athens'),
('ARN','Stockholm Arlanda Airport','Stockholm','Sweden','Europe/Stockholm'),
('GOT','Gothenburg Landvetter Airport','Gothenburg','Sweden','Europe/Stockholm'),
('MMX','Malmo Airport','Malmo','Sweden','Europe/Stockholm'),
('CPH','Copenhagen Airport Kastrup','Copenhagen','Denmark','Europe/Copenhagen'),
('OSL','Oslo Gardermoen Airport','Oslo','Norway','Europe/Oslo'),
('BGO','Bergen Flesland Airport','Bergen','Norway','Europe/Oslo'),
('SVG','Stavanger Sola Airport','Stavanger','Norway','Europe/Oslo'),
('HEL','Helsinki-Vantaa Airport','Helsinki','Finland','Europe/Helsinki'),
('OUL','Oulu Airport','Oulu','Finland','Europe/Helsinki'),
('RVN','Rovaniemi Airport','Rovaniemi','Finland','Europe/Helsinki'),
('TLL','Lennart Meri Tallinn Airport','Tallinn','Estonia','Europe/Tallinn'),
('RIX','Riga International Airport','Riga','Latvia','Europe/Riga'),
('VNO','Vilnius International Airport','Vilnius','Lithuania','Europe/Vilnius'),
('HEL','Helsinki Vantaa Airport','Helsinki','Finland','Europe/Helsinki'),
('WAW','Warsaw Chopin Airport','Warsaw','Poland','Europe/Warsaw'),
('KRK','John Paul II International Krakow-Balice','Krakow','Poland','Europe/Warsaw'),
('GDN','Lech Walesa Airport Gdansk','Gdansk','Poland','Europe/Warsaw'),
('WRO','Wroclaw Nicolas Copernicus Airport','Wroclaw','Poland','Europe/Warsaw'),
('PRG','Vaclav Havel Airport Prague','Prague','Czech Republic','Europe/Prague'),
('BUD','Budapest Ferenc Liszt International','Budapest','Hungary','Europe/Budapest'),
('BEG','Nikola Tesla Airport','Belgrade','Serbia','Europe/Belgrade'),
('SOF','Sofia Airport','Sofia','Bulgaria','Europe/Sofia'),
('OTP','Henri Coanda International','Bucharest','Romania','Europe/Bucharest'),
('CLJ','Cluj Avram Iancu International','Cluj-Napoca','Romania','Europe/Bucharest'),
('KBP','Boryspil International','Kyiv','Ukraine','Europe/Kiev'),
('IEV','Igor Sikorsky Kyiv International','Kyiv','Ukraine','Europe/Kiev'),
('LWO','Lviv Danylo Halytskyi International','Lviv','Ukraine','Europe/Kiev'),
('MSQ','Minsk National Airport','Minsk','Belarus','Europe/Minsk'),
('TBS','Tbilisi International Airport','Tbilisi','Georgia','Asia/Tbilisi'),
('EVN','Zvartnots International','Yerevan','Armenia','Asia/Yerevan'),
('GYD','Heydar Aliyev International','Baku','Azerbaijan','Asia/Baku'),
('IST','Istanbul Airport','Istanbul','Turkey','Europe/Istanbul'),
('SAW','Sabiha Gokcen International','Istanbul','Turkey','Europe/Istanbul'),
('AYT','Antalya Airport','Antalya','Turkey','Europe/Istanbul'),
('DLM','Dalaman Airport','Dalaman','Turkey','Europe/Istanbul'),
('ADB','Adnan Menderes Airport','Izmir','Turkey','Europe/Istanbul'),
('ESB','Ankara Esenboga International','Ankara','Turkey','Europe/Istanbul'),
('SKP','Skopje Alexander the Great Airport','Skopje','North Macedonia','Europe/Skopje'),
('TIA','Tirana Rinas Mother Teresa Airport','Tirana','Albania','Europe/Tirane'),
('DBV','Dubrovnik Airport','Dubrovnik','Croatia','Europe/Zagreb'),
('ZAG','Zagreb Airport','Zagreb','Croatia','Europe/Zagreb'),
('SPU','Split Airport','Split','Croatia','Europe/Zagreb'),
('LJU','Ljubljana Joze Pucnik Airport','Ljubljana','Slovenia','Europe/Ljubljana'),
('SJJ','Sarajevo International Airport','Sarajevo','Bosnia and Herzegovina','Europe/Sarajevo'),
('TGD','Podgorica Airport','Podgorica','Montenegro','Europe/Podgorica'),
('PRN','Pristina Adem Jashari International','Pristina','Kosovo','Europe/Belgrade'),
('KIV','Chisinau International Airport','Chisinau','Moldova','Europe/Chisinau'),
('KEF','Keflavik International Airport','Reykjavik','Iceland','Atlantic/Reykjavik'),
('DUB','Dublin Airport','Dublin','Ireland','Europe/Dublin'),
('SNN','Shannon Airport','Shannon','Ireland','Europe/Dublin'),

-- ═══════════════════════════════════════════════════════════
-- MIDDLE EAST
-- ═══════════════════════════════════════════════════════════
('DXB','Dubai International','Dubai','United Arab Emirates','Asia/Dubai'),
('AUH','Abu Dhabi International','Abu Dhabi','United Arab Emirates','Asia/Dubai'),
('DWC','Al Maktoum International','Dubai','United Arab Emirates','Asia/Dubai'),
('DOH','Hamad International','Doha','Qatar','Asia/Qatar'),
('RUH','King Khalid International','Riyadh','Saudi Arabia','Asia/Riyadh'),
('JED','King Abdulaziz International','Jeddah','Saudi Arabia','Asia/Riyadh'),
('DMM','King Fahd International','Dammam','Saudi Arabia','Asia/Riyadh'),
('MED','Prince Mohammad Bin Abdulaziz International','Medina','Saudi Arabia','Asia/Riyadh'),
('KWI','Kuwait International','Kuwait City','Kuwait','Asia/Kuwait'),
('BAH','Bahrain International','Manama','Bahrain','Asia/Bahrain'),
('MCT','Muscat International','Muscat','Oman','Asia/Muscat'),
('SLL','Salalah Airport','Salalah','Oman','Asia/Muscat'),
('BEY','Beirut Rafic Hariri International','Beirut','Lebanon','Asia/Beirut'),
('AMM','Queen Alia International','Amman','Jordan','Asia/Amman'),
('DAM','Damascus International','Damascus','Syria','Asia/Damascus'),
('BGW','Baghdad International','Baghdad','Iraq','Asia/Baghdad'),
('TLV','Ben Gurion International','Tel Aviv','Israel','Asia/Jerusalem'),
('GYD','Heydar Aliyev International','Baku','Azerbaijan','Asia/Baku'),
('THR','Imam Khomeini International','Tehran','Iran','Asia/Tehran'),
('IKA','Imam Khomeini International','Tehran','Iran','Asia/Tehran'),
('MHD','Mashhad International','Mashhad','Iran','Asia/Tehran'),
('SYZ','Shiraz International','Shiraz','Iran','Asia/Tehran'),
('IFN','Isfahan International','Isfahan','Iran','Asia/Tehran'),
('CAI','Cairo International','Cairo','Egypt','Africa/Cairo'),
('HRG','Hurghada International','Hurghada','Egypt','Africa/Cairo'),
('SSH','Sharm el-Sheikh International','Sharm el-Sheikh','Egypt','Africa/Cairo'),
('LXR','Luxor International','Luxor','Egypt','Africa/Cairo'),
('ASW','Aswan International','Aswan','Egypt','Africa/Cairo'),
('ATW','Atyrau Airport','Atyrau','Kazakhstan','Asia/Atyrau'),
('ALA','Almaty International','Almaty','Kazakhstan','Asia/Almaty'),
('NQZ','Nur-Sultan Nursultan Nazarbayev International','Nur-Sultan','Kazakhstan','Asia/Almaty'),

-- ═══════════════════════════════════════════════════════════
-- AFRICA
-- ═══════════════════════════════════════════════════════════
('JNB','O.R. Tambo International','Johannesburg','South Africa','Africa/Johannesburg'),
('CPT','Cape Town International','Cape Town','South Africa','Africa/Johannesburg'),
('DUR','King Shaka International','Durban','South Africa','Africa/Johannesburg'),
('PLZ','Port Elizabeth International','Port Elizabeth','South Africa','Africa/Johannesburg'),
('NBO','Jomo Kenyatta International','Nairobi','Kenya','Africa/Nairobi'),
('MBA','Moi International','Mombasa','Kenya','Africa/Nairobi'),
('DAR','Julius Nyerere International','Dar es Salaam','Tanzania','Africa/Dar_es_Salaam'),
('JRO','Kilimanjaro International','Arusha','Tanzania','Africa/Dar_es_Salaam'),
('EBB','Entebbe International','Kampala','Uganda','Africa/Kampala'),
('ADD','Addis Ababa Bole International','Addis Ababa','Ethiopia','Africa/Addis_Ababa'),
('LOS','Murtala Muhammed International','Lagos','Nigeria','Africa/Lagos'),
('ABV','Nnamdi Azikiwe International','Abuja','Nigeria','Africa/Lagos'),
('KAN','Mallam Aminu Kano International','Kano','Nigeria','Africa/Lagos'),
('ACC','Kotoka International','Accra','Ghana','Africa/Accra'),
('ABJ','Port Bouet Airport','Abidjan','Ivory Coast','Africa/Abidjan'),
('DKR','Leopold Sedar Senghor International','Dakar','Senegal','Africa/Dakar'),
('ROB','Roberts International','Monrovia','Liberia','Africa/Monrovia'),
('FNA','Lungi International','Freetown','Sierra Leone','Africa/Freetown'),
('BJL','Banjul International','Banjul','Gambia','Africa/Banjul'),
('CMN','Mohammed V International','Casablanca','Morocco','Africa/Casablanca'),
('RAK','Marrakech Menara Airport','Marrakesh','Morocco','Africa/Casablanca'),
('TNG','Tangier Ibn Battouta Airport','Tangier','Morocco','Africa/Casablanca'),
('AGA','Agadir Al-Massira Airport','Agadir','Morocco','Africa/Casablanca'),
('TUN','Tunis-Carthage International','Tunis','Tunisia','Africa/Tunis'),
('DJE','Djerba-Zarzis International','Djerba','Tunisia','Africa/Tunis'),
('ALG','Houari Boumediene Airport','Algiers','Algeria','Africa/Algiers'),
('TLM','Zenata Messali El Hadj Airport','Tlemcen','Algeria','Africa/Algiers'),
('TRN','Tripoli International','Tripoli','Libya','Africa/Tripoli'),
('NIM','Diori Hamani International','Niamey','Niger','Africa/Niamey'),
('OUA','Thomas Sankara International','Ouagadougou','Burkina Faso','Africa/Ouagadougou'),
('BKO','Bamako Senou International','Bamako','Mali','Africa/Bamako'),
('COO','Cotonou Cadjehoun Airport','Cotonou','Benin','Africa/Porto-Novo'),
('SSG','Santa Isabel Airport','Malabo','Equatorial Guinea','Africa/Malabo'),
('DLA','Douala International','Douala','Cameroon','Africa/Douala'),
('NSI','Yaounde Nsimalen International','Yaounde','Cameroon','Africa/Douala'),
('LBV','Leon M\'ba International','Libreville','Gabon','Africa/Libreville'),
('BZV','Maya-Maya Airport','Brazzaville','Congo','Africa/Brazzaville'),
('FIH','Ndjili International','Kinshasa','DR Congo','Africa/Kinshasa'),
('FBM','Lubumbashi International','Lubumbashi','DR Congo','Africa/Lubumbashi'),
('LUN','Kenneth Kaunda International','Lusaka','Zambia','Africa/Lusaka'),
('HRE','Robert Gabriel Mugabe International','Harare','Zimbabwe','Africa/Harare'),
('BLZ','Chileka International','Blantyre','Malawi','Africa/Blantyre'),
('LLW','Lilongwe International','Lilongwe','Malawi','Africa/Blantyre'),
('MPM','Maputo International','Maputo','Mozambique','Africa/Maputo'),
('WDH','Hosea Kutako International','Windhoek','Namibia','Africa/Windhoek'),
('GBE','Sir Seretse Khama International','Gaborone','Botswana','Africa/Gaborone'),
('MRU','Sir Seewoosagur Ramgoolam International','Port Louis','Mauritius','Indian/Mauritius'),
('RUN','Roland Garros Airport','Saint-Denis','Reunion','Indian/Reunion'),
('TNR','Ivato International','Antananarivo','Madagascar','Indian/Antananarivo'),
('SEZ','Seychelles International','Mahe Island','Seychelles','Indian/Mahe'),
('MHQ','Mariehamn Airport','Mariehamn','Aland Islands','Europe/Mariehamn'),
('HAH','Moroni Hahaya International','Moroni','Comoros','Indian/Comoro'),
('ASL','Marshall Islands International','Marshall Islands','Marshall Islands','Pacific/Majuro'),

-- ═══════════════════════════════════════════════════════════
-- SOUTH ASIA
-- ═══════════════════════════════════════════════════════════
('DEL','Indira Gandhi International','New Delhi','India','Asia/Kolkata'),
('BOM','Chhatrapati Shivaji Maharaj International','Mumbai','India','Asia/Kolkata'),
('BLR','Kempegowda International','Bangalore','India','Asia/Kolkata'),
('MAA','Chennai International','Chennai','India','Asia/Kolkata'),
('HYD','Rajiv Gandhi International','Hyderabad','India','Asia/Kolkata'),
('CCU','Netaji Subhas Chandra Bose International','Kolkata','India','Asia/Kolkata'),
('COK','Cochin International','Kochi','India','Asia/Kolkata'),
('TRV','Trivandrum International','Thiruvananthapuram','India','Asia/Kolkata'),
('AMD','Sardar Vallabhbhai Patel International','Ahmedabad','India','Asia/Kolkata'),
('PNQ','Pune Airport','Pune','India','Asia/Kolkata'),
('GOI','Goa International','Goa','India','Asia/Kolkata'),
('JAI','Jaipur International','Jaipur','India','Asia/Kolkata'),
('LKO','Chaudhary Charan Singh International','Lucknow','India','Asia/Kolkata'),
('PAT','Lok Nayak Jayaprakash Airport','Patna','India','Asia/Kolkata'),
('VNS','Lal Bahadur Shastri International','Varanasi','India','Asia/Kolkata'),
('NAG','Dr. Babasaheb Ambedkar International','Nagpur','India','Asia/Kolkata'),
('IXB','Bagdogra Airport','Siliguri','India','Asia/Kolkata'),
('CCJ','Calicut International','Kozhikode','India','Asia/Kolkata'),
('KTM','Tribhuvan International','Kathmandu','Nepal','Asia/Kathmandu'),
('DAC','Hazrat Shahjalal International','Dhaka','Bangladesh','Asia/Dhaka'),
('CGP','Shah Amanat International','Chittagong','Bangladesh','Asia/Dhaka'),
('CMB','Bandaranaike International','Colombo','Sri Lanka','Asia/Colombo'),
('KHI','Jinnah International','Karachi','Pakistan','Asia/Karachi'),
('LHE','Allama Iqbal International','Lahore','Pakistan','Asia/Karachi'),
('ISB','Islamabad International','Islamabad','Pakistan','Asia/Karachi'),
('PEW','Peshawar International','Peshawar','Pakistan','Asia/Karachi'),
('MLE','Velana International','Male','Maldives','Indian/Maldives'),
('RGN','Yangon International','Yangon','Myanmar','Asia/Rangoon'),

-- ═══════════════════════════════════════════════════════════
-- SOUTHEAST ASIA
-- ═══════════════════════════════════════════════════════════
('SIN','Singapore Changi Airport','Singapore','Singapore','Asia/Singapore'),
('KUL','Kuala Lumpur International','Kuala Lumpur','Malaysia','Asia/Kuala_Lumpur'),
('BKK','Suvarnabhumi Airport','Bangkok','Thailand','Asia/Bangkok'),
('DMK','Don Mueang International','Bangkok','Thailand','Asia/Bangkok'),
('HKT','Phuket International','Phuket','Thailand','Asia/Bangkok'),
('CNX','Chiang Mai International','Chiang Mai','Thailand','Asia/Bangkok'),
('SGN','Tan Son Nhat International','Ho Chi Minh City','Vietnam','Asia/Ho_Chi_Minh'),
('HAN','Noi Bai International','Hanoi','Vietnam','Asia/Ho_Chi_Minh'),
('DAD','Da Nang International','Da Nang','Vietnam','Asia/Ho_Chi_Minh'),
('PNH','Phnom Penh International','Phnom Penh','Cambodia','Asia/Phnom_Penh'),
('REP','Siem Reap International','Siem Reap','Cambodia','Asia/Phnom_Penh'),
('VTE','Wattay International','Vientiane','Laos','Asia/Vientiane'),
('RGN','Yangon International','Yangon','Myanmar','Asia/Rangoon'),
('MDL','Mandalay International','Mandalay','Myanmar','Asia/Rangoon'),
('MNL','Ninoy Aquino International','Manila','Philippines','Asia/Manila'),
('CEB','Mactan-Cebu International','Cebu','Philippines','Asia/Manila'),
('DVO','Francisco Bangoy International','Davao','Philippines','Asia/Manila'),
('CGK','Soekarno-Hatta International','Jakarta','Indonesia','Asia/Jakarta'),
('DPS','Ngurah Rai International','Bali','Indonesia','Asia/Makassar'),
('SUB','Juanda International','Surabaya','Indonesia','Asia/Jakarta'),
('UPG','Sultan Hasanuddin International','Makassar','Indonesia','Asia/Makassar'),
('BTH','Hang Nadim International','Batam','Indonesia','Asia/Jakarta'),
('BPN','Sultan Aji Muhammad Sulaiman International','Balikpapan','Indonesia','Asia/Makassar'),

-- ═══════════════════════════════════════════════════════════
-- EAST ASIA
-- ═══════════════════════════════════════════════════════════
('PEK','Beijing Capital International','Beijing','China','Asia/Shanghai'),
('PKX','Beijing Daxing International','Beijing','China','Asia/Shanghai'),
('PVG','Shanghai Pudong International','Shanghai','China','Asia/Shanghai'),
('SHA','Shanghai Hongqiao International','Shanghai','China','Asia/Shanghai'),
('CAN','Guangzhou Baiyun International','Guangzhou','China','Asia/Shanghai'),
('CTU','Chengdu Shuangliu International','Chengdu','China','Asia/Shanghai'),
('SZX','Shenzhen Bao\'an International','Shenzhen','China','Asia/Shanghai'),
('XIY','Xian Xianyang International','Xian','China','Asia/Shanghai'),
('KMG','Kunming Changshui International','Kunming','China','Asia/Shanghai'),
('WUH','Wuhan Tianhe International','Wuhan','China','Asia/Shanghai'),
('CSX','Changsha Huanghua International','Changsha','China','Asia/Shanghai'),
('HAK','Haikou Meilan International','Haikou','China','Asia/Shanghai'),
('NKG','Nanjing Lukou International','Nanjing','China','Asia/Shanghai'),
('HGH','Hangzhou Xiaoshan International','Hangzhou','China','Asia/Shanghai'),
('XMN','Xiamen Gaoqi International','Xiamen','China','Asia/Shanghai'),
('CKG','Chongqing Jiangbei International','Chongqing','China','Asia/Shanghai'),
('TSN','Tianjin Binhai International','Tianjin','China','Asia/Shanghai'),
('DLC','Dalian Zhoushuizi International','Dalian','China','Asia/Shanghai'),
('SHE','Shenyang Taoxian International','Shenyang','China','Asia/Shanghai'),
('HRB','Harbin Taiping International','Harbin','China','Asia/Shanghai'),
('SYX','Sanya Phoenix International','Sanya','China','Asia/Shanghai'),
('HKG','Hong Kong International','Hong Kong','Hong Kong','Asia/Hong_Kong'),
('MFM','Macau International','Macau','Macau','Asia/Macau'),
('TPE','Taiwan Taoyuan International','Taipei','Taiwan','Asia/Taipei'),
('RMQ','Taichung Airport','Taichung','Taiwan','Asia/Taipei'),
('TNN','Tainan Airport','Tainan','Taiwan','Asia/Taipei'),
('KHH','Kaohsiung International','Kaohsiung','Taiwan','Asia/Taipei'),
('ICN','Incheon International','Seoul','South Korea','Asia/Seoul'),
('GMP','Gimpo International','Seoul','South Korea','Asia/Seoul'),
('PUS','Gimhae International','Busan','South Korea','Asia/Seoul'),
('CJU','Jeju International','Jeju','South Korea','Asia/Seoul'),
('NRT','Narita International','Tokyo','Japan','Asia/Tokyo'),
('HND','Tokyo Haneda International','Tokyo','Japan','Asia/Tokyo'),
('KIX','Kansai International','Osaka','Japan','Asia/Tokyo'),
('ITM','Osaka Itami Airport','Osaka','Japan','Asia/Tokyo'),
('NGO','Chubu Centrair International','Nagoya','Japan','Asia/Tokyo'),
('CTS','New Chitose Airport','Sapporo','Japan','Asia/Tokyo'),
('FUK','Fukuoka Airport','Fukuoka','Japan','Asia/Tokyo'),
('OKA','Naha Airport','Okinawa','Japan','Asia/Tokyo'),
('MNL','Ninoy Aquino International','Manila','Philippines','Asia/Manila'),
('ULN','Chinggis Khaan International','Ulaanbaatar','Mongolia','Asia/Ulaanbaatar'),

-- Central Asia
('ALA','Almaty International','Almaty','Kazakhstan','Asia/Almaty'),
('NQZ','Nursultan Nazarbayev International','Nur-Sultan','Kazakhstan','Asia/Almaty'),
('TAS','Islam Karimov Tashkent International','Tashkent','Uzbekistan','Asia/Tashkent'),
('SKD','Samarkand International','Samarkand','Uzbekistan','Asia/Tashkent'),
('ASB','Ashgabat International','Ashgabat','Turkmenistan','Asia/Ashgabat'),
('DYU','Dushanbe International','Dushanbe','Tajikistan','Asia/Dushanbe'),
('FRU','Manas International','Bishkek','Kyrgyzstan','Asia/Bishkek'),
('KBL','Hamid Karzai International','Kabul','Afghanistan','Asia/Kabul'),

-- ═══════════════════════════════════════════════════════════
-- OCEANIA
-- ═══════════════════════════════════════════════════════════
('SYD','Sydney Kingsford Smith Airport','Sydney','Australia','Australia/Sydney'),
('MEL','Melbourne Airport','Melbourne','Australia','Australia/Melbourne'),
('BNE','Brisbane Airport','Brisbane','Australia','Australia/Brisbane'),
('PER','Perth Airport','Perth','Australia','Australia/Perth'),
('ADL','Adelaide Airport','Adelaide','Australia','Australia/Adelaide'),
('OOL','Gold Coast Airport','Gold Coast','Australia','Australia/Brisbane'),
('CBR','Canberra Airport','Canberra','Australia','Australia/Sydney'),
('HBA','Hobart Airport','Hobart','Australia','Australia/Hobart'),
('DRW','Darwin International Airport','Darwin','Australia','Australia/Darwin'),
('TSV','Townsville Airport','Townsville','Australia','Australia/Brisbane'),
('CNS','Cairns Airport','Cairns','Australia','Australia/Brisbane'),
('AKL','Auckland Airport','Auckland','New Zealand','Pacific/Auckland'),
('WLG','Wellington International','Wellington','New Zealand','Pacific/Auckland'),
('CHC','Christchurch International','Christchurch','New Zealand','Pacific/Auckland'),
('ZQN','Queenstown Airport','Queenstown','New Zealand','Pacific/Auckland'),
('DUD','Dunedin Airport','Dunedin','New Zealand','Pacific/Auckland'),
('NAN','Nadi International','Nadi','Fiji','Pacific/Fiji'),
('SUV','Nausori Airport','Suva','Fiji','Pacific/Fiji'),
('APW','Faleolo International','Apia','Samoa','Pacific/Apia'),
('TBU','Fua\'amotu International','Nukualofa','Tonga','Pacific/Tongatapu'),
('PPT','Tahiti Faaa International','Papeete','French Polynesia','Pacific/Tahiti'),
('HIR','Honiara International','Honiara','Solomon Islands','Pacific/Guadalcanal'),
('VLI','Port Vila Bauerfield International','Port Vila','Vanuatu','Pacific/Efate'),
('GUM','Antonio B. Won Pat International','Hagatna','Guam','Pacific/Guam'),
('SPN','Saipan International','Saipan','Northern Mariana Islands','Pacific/Saipan'),
('MAJ','Marshall Islands International','Majuro','Marshall Islands','Pacific/Majuro'),
('TRW','Bonriki International','Tarawa','Kiribati','Pacific/Tarawa'),
('FUN','Funafuti International','Funafuti','Tuvalu','Pacific/Funafuti'),
('IUE','Niue Airport','Alofi','Niue','Pacific/Niue'),
('RAR','Rarotonga International','Avarua','Cook Islands','Pacific/Rarotonga'),
('NOU','La Tontouta International','Noumea','New Caledonia','Pacific/Noumea'),
('POM','Jacksons International','Port Moresby','Papua New Guinea','Pacific/Port_Moresby'),
('PNI','Pohnpei Airport','Palikir','Micronesia','Pacific/Pohnpei');
